Fix Valgrind failure handling in Docker

diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -1,17 +1,29 @@
 #!/bin/bash
 
 vg_verify() {
+   ulimit -n 1024
+
    valgrind --version
    valgrind --tool=memcheck --leak-check=full --track-origins=no $1 2>&1 | tee valgrind.log
+   vg_status=${PIPESTATUS[0]}
+
+   if [ "$vg_status" -ne 0 ]; then
+     echo "Valgrind failed"
+     rm -f valgrind.log
+     exit "$vg_status"
+   fi
+
    if [ "$2" != "--no-leak-check" ]; then
      if grep -E "definitely lost: [1-9]|indirectly lost: [1-9]|possibly lost: [1-9]" valgrind.log; then
        echo "Memory leak detected"
+       rm -f valgrind.log
        exit 1
      fi
    else
      echo "Leak detection skipped"
    fi
-   rm valgrind.log
+
+   rm -f valgrind.log
 }
 
 db_init() {
